package mcp

import (
	"github.com/hcd233/ossinsight-mcp/internal/repo/ossinsight"
	"github.com/mark3labs/mcp-go/mcp"
)

// ListTrendingReposSchema 获取趋势仓库列表的工具
//
//	@author centonhuang
//	@update 2025-06-12 20:41:39
func ListTrendingReposSchema() mcp.Tool {
	return mcp.NewTool(
		"ListTrendingRepos",
		mcp.WithDescription("Get trending GitHub repositories based on various time periods and programming languages. This tool helps discover popular and rapidly growing repositories in the GitHub ecosystem."),
		mcp.WithString("period",
			mcp.Description("Time period for fetching trending repositories. Choose from past 24 hours, past week, past month, or past 3 months to see repositories that gained popularity during that timeframe."),
			mcp.Enum(
				ossinsight.ListTrendReposPeriodPast24Hours,
				ossinsight.ListTrendReposPeriodPastWeek,
				ossinsight.ListTrendReposPeriodPastMonth,
				ossinsight.ListTrendReposPeriodPast3Months,
			),
			mcp.Required(),
		),
		mcp.WithString("language",
			mcp.Description("Programming language filter for trending repositories. Select a specific programming language to see trending repositories in that language, or choose 'All' to see repositories across all programming languages."),
			mcp.Enum(
				ossinsight.LanguageAll,
				ossinsight.LanguageJavaScript,
				ossinsight.LanguageJava,
				ossinsight.LanguagePython,
				ossinsight.LanguagePHP,
				ossinsight.LanguageCPlusPlus,
				ossinsight.LanguageCSharp,
				ossinsight.LanguageTypeScript,
				ossinsight.LanguageShell,
				ossinsight.LanguageC,
				ossinsight.LanguageRuby,
				ossinsight.LanguageRust,
				ossinsight.LanguageGo,
				ossinsight.LanguageKotlin,
				ossinsight.LanguageHCL,
				ossinsight.LanguagePowerShell,
				ossinsight.LanguageCMake,
				ossinsight.LanguageGroovy,
				ossinsight.LanguagePLpgSQL,
				ossinsight.LanguageTSQL,
				ossinsight.LanguageDart,
				ossinsight.LanguageSwift,
				ossinsight.LanguageHTML,
				ossinsight.LanguageCSS,
				ossinsight.LanguageElixir,
				ossinsight.LanguageHaskell,
				ossinsight.LanguageSolidity,
				ossinsight.LanguageAssembly,
				ossinsight.LanguageR,
				ossinsight.LanguageScala,
				ossinsight.LanguageJulia,
				ossinsight.LanguageLua,
				ossinsight.LanguageClojure,
				ossinsight.LanguageErlang,
				ossinsight.LanguageCommonLisp,
				ossinsight.LanguageEmacsLisp,
				ossinsight.LanguageOCaml,
				ossinsight.LanguageMATLAB,
				ossinsight.LanguageObjectiveC,
				ossinsight.LanguagePerl,
				ossinsight.LanguageFortran,
			),
			mcp.Required(),
		),
		mcp.WithNumber("limit",
			mcp.Description("Maximum number of repositories to return. Range from 1 to 100."),
			mcp.DefaultNumber(10),
			mcp.Min(1),
			mcp.Max(100),
		),
	)
}

// GetRepoRankingSchema 获取仓库排名的工具
func GetRepoRankingSchema() mcp.Tool {
	return mcp.NewTool(
		"GetRepoRanking",
		mcp.WithDescription("Get GitHub repository rankings based on various metrics like stars, forks, commits, contributors, pull requests, and issues. This tool helps identify the most popular and active repositories in the GitHub ecosystem."),
		mcp.WithString("ranking_type",
			mcp.Description("Type of ranking to fetch. Choose from stars, forks, commits, contributors, pull_requests, or issues to see repositories ranked by different metrics."),
			mcp.Enum(
				ossinsight.RankingTypeStars,
				ossinsight.RankingTypeForks,
				ossinsight.RankingTypeCommits,
				ossinsight.RankingTypeContributors,
				ossinsight.RankingTypePullRequests,
				ossinsight.RankingTypeIssues,
			),
			mcp.Required(),
		),
		mcp.WithString("time_range",
			mcp.Description("Time range for the ranking data. Choose from past 24 hours, past week, past month, past 3 months, past year, or all time to see rankings for different periods."),
			mcp.Enum(
				ossinsight.TimeRangePast24Hours,
				ossinsight.TimeRangePastWeek,
				ossinsight.TimeRangePastMonth,
				ossinsight.TimeRangePast3Months,
				ossinsight.TimeRangePastYear,
				ossinsight.TimeRangeAllTime,
			),
			mcp.Required(),
		),
		mcp.WithString("language",
			mcp.Description("Programming language filter for repository rankings. Select a specific programming language to see rankings for repositories in that language, or choose 'All' to see rankings across all programming languages."),
			mcp.Enum(
				ossinsight.LanguageAll,
				ossinsight.LanguageJavaScript,
				ossinsight.LanguageJava,
				ossinsight.LanguagePython,
				ossinsight.LanguagePHP,
				ossinsight.LanguageCPlusPlus,
				ossinsight.LanguageCSharp,
				ossinsight.LanguageTypeScript,
				ossinsight.LanguageShell,
				ossinsight.LanguageC,
				ossinsight.LanguageRuby,
				ossinsight.LanguageRust,
				ossinsight.LanguageGo,
				ossinsight.LanguageKotlin,
				ossinsight.LanguageHCL,
				ossinsight.LanguagePowerShell,
				ossinsight.LanguageCMake,
				ossinsight.LanguageGroovy,
				ossinsight.LanguagePLpgSQL,
				ossinsight.LanguageTSQL,
				ossinsight.LanguageDart,
				ossinsight.LanguageSwift,
				ossinsight.LanguageHTML,
				ossinsight.LanguageCSS,
				ossinsight.LanguageElixir,
				ossinsight.LanguageHaskell,
				ossinsight.LanguageSolidity,
				ossinsight.LanguageAssembly,
				ossinsight.LanguageR,
				ossinsight.LanguageScala,
				ossinsight.LanguageJulia,
				ossinsight.LanguageLua,
				ossinsight.LanguageClojure,
				ossinsight.LanguageErlang,
				ossinsight.LanguageCommonLisp,
				ossinsight.LanguageEmacsLisp,
				ossinsight.LanguageOCaml,
				ossinsight.LanguageMATLAB,
				ossinsight.LanguageObjectiveC,
				ossinsight.LanguagePerl,
				ossinsight.LanguageFortran,
			),
		),
		mcp.WithNumber("limit",
			mcp.Description("Maximum number of repositories to return. Range from 1 to 100."),
			mcp.DefaultNumber(10),
			mcp.Min(1),
			mcp.Max(100),
		),
	)
}

// GetDeveloperRankingSchema 获取开发者排名的工具
func GetDeveloperRankingSchema() mcp.Tool {
	return mcp.NewTool(
		"GetDeveloperRanking",
		mcp.WithDescription("Get GitHub developer rankings based on various metrics like stars, forks, commits, pull requests, and issues. This tool helps identify the most active and influential developers in the GitHub ecosystem."),
		mcp.WithString("ranking_type",
			mcp.Description("Type of ranking to fetch. Choose from stars, forks, commits, pull_requests, or issues to see developers ranked by different metrics."),
			mcp.Enum(
				ossinsight.RankingTypeStars,
				ossinsight.RankingTypeForks,
				ossinsight.RankingTypeCommits,
				ossinsight.RankingTypePullRequests,
				ossinsight.RankingTypeIssues,
			),
			mcp.Required(),
		),
		mcp.WithString("time_range",
			mcp.Description("Time range for the ranking data. Choose from past 24 hours, past week, past month, past 3 months, past year, or all time to see rankings for different periods."),
			mcp.Enum(
				ossinsight.TimeRangePast24Hours,
				ossinsight.TimeRangePastWeek,
				ossinsight.TimeRangePastMonth,
				ossinsight.TimeRangePast3Months,
				ossinsight.TimeRangePastYear,
				ossinsight.TimeRangeAllTime,
			),
			mcp.Required(),
		),
		mcp.WithString("language",
			mcp.Description("Programming language filter for developer rankings. Select a specific programming language to see rankings for developers active in that language, or choose 'All' to see rankings across all programming languages."),
			mcp.Enum(
				ossinsight.LanguageAll,
				ossinsight.LanguageJavaScript,
				ossinsight.LanguageJava,
				ossinsight.LanguagePython,
				ossinsight.LanguagePHP,
				ossinsight.LanguageCPlusPlus,
				ossinsight.LanguageCSharp,
				ossinsight.LanguageTypeScript,
				ossinsight.LanguageShell,
				ossinsight.LanguageC,
				ossinsight.LanguageRuby,
				ossinsight.LanguageRust,
				ossinsight.LanguageGo,
				ossinsight.LanguageKotlin,
				ossinsight.LanguageHCL,
				ossinsight.LanguagePowerShell,
				ossinsight.LanguageCMake,
				ossinsight.LanguageGroovy,
				ossinsight.LanguagePLpgSQL,
				ossinsight.LanguageTSQL,
				ossinsight.LanguageDart,
				ossinsight.LanguageSwift,
				ossinsight.LanguageHTML,
				ossinsight.LanguageCSS,
				ossinsight.LanguageElixir,
				ossinsight.LanguageHaskell,
				ossinsight.LanguageSolidity,
				ossinsight.LanguageAssembly,
				ossinsight.LanguageR,
				ossinsight.LanguageScala,
				ossinsight.LanguageJulia,
				ossinsight.LanguageLua,
				ossinsight.LanguageClojure,
				ossinsight.LanguageErlang,
				ossinsight.LanguageCommonLisp,
				ossinsight.LanguageEmacsLisp,
				ossinsight.LanguageOCaml,
				ossinsight.LanguageMATLAB,
				ossinsight.LanguageObjectiveC,
				ossinsight.LanguagePerl,
				ossinsight.LanguageFortran,
			),
		),
		mcp.WithNumber("limit",
			mcp.Description("Maximum number of developers to return. Range from 1 to 100."),
			mcp.DefaultNumber(10),
			mcp.Min(1),
			mcp.Max(100),
		),
	)
}

// GetCollectionsSchema 获取收藏夹列表的工具
func GetCollectionsSchema() mcp.Tool {
	return mcp.NewTool(
		"GetCollections",
		mcp.WithDescription("Get GitHub collections (curated lists of repositories) based on various criteria. This tool helps discover curated collections of repositories created by the community."),
		mcp.WithString("collection_type",
			mcp.Description("Type of collections to fetch. Choose from 'all' for all collections, 'hot' for popular collections, or 'user' for user-created collections."),
			mcp.Enum(
				ossinsight.CollectionTypeAll,
				ossinsight.CollectionTypeHot,
				ossinsight.CollectionTypeUser,
			),
			mcp.Required(),
		),
		mcp.WithString("time_range",
			mcp.Description("Time range for the collections data. Choose from past 24 hours, past week, past month, past 3 months, past year, or all time to see collections for different periods."),
			mcp.Enum(
				ossinsight.TimeRangePast24Hours,
				ossinsight.TimeRangePastWeek,
				ossinsight.TimeRangePastMonth,
				ossinsight.TimeRangePast3Months,
				ossinsight.TimeRangePastYear,
				ossinsight.TimeRangeAllTime,
			),
			mcp.Required(),
		),
		mcp.WithNumber("limit",
			mcp.Description("Maximum number of collections to return. Range from 1 to 100."),
			mcp.DefaultNumber(10),
			mcp.Min(1),
			mcp.Max(100),
		),
	)
}

// GetHotCollectionsSchema 获取热门收藏夹的工具
func GetHotCollectionsSchema() mcp.Tool {
	return mcp.NewTool(
		"GetHotCollections",
		mcp.WithDescription("Get hot GitHub collections that are currently trending and popular. This tool helps discover the most popular curated lists of repositories."),
		mcp.WithString("time_range",
			mcp.Description("Time range for the hot collections data. Choose from past 24 hours, past week, past month, past 3 months, past year, or all time to see hot collections for different periods."),
			mcp.Enum(
				ossinsight.TimeRangePast24Hours,
				ossinsight.TimeRangePastWeek,
				ossinsight.TimeRangePastMonth,
				ossinsight.TimeRangePast3Months,
				ossinsight.TimeRangePastYear,
				ossinsight.TimeRangeAllTime,
			),
			mcp.Required(),
		),
		mcp.WithNumber("limit",
			mcp.Description("Maximum number of hot collections to return. Range from 1 to 100."),
			mcp.DefaultNumber(10),
			mcp.Min(1),
			mcp.Max(100),
		),
	)
}

// GetCollectionReposSchema 获取收藏夹仓库列表的工具
func GetCollectionReposSchema() mcp.Tool {
	return mcp.NewTool(
		"GetCollectionRepos",
		mcp.WithDescription("Get repositories from a specific GitHub collection. This tool helps explore the repositories curated in a particular collection."),
		mcp.WithString("collection_id",
			mcp.Description("ID of the collection to fetch repositories from."),
			mcp.Required(),
		),
		mcp.WithString("time_range",
			mcp.Description("Time range for the collection repositories data. Choose from past 24 hours, past week, past month, past 3 months, past year, or all time to see repositories for different periods."),
			mcp.Enum(
				ossinsight.TimeRangePast24Hours,
				ossinsight.TimeRangePastWeek,
				ossinsight.TimeRangePastMonth,
				ossinsight.TimeRangePast3Months,
				ossinsight.TimeRangePastYear,
				ossinsight.TimeRangeAllTime,
			),
			mcp.Required(),
		),
		mcp.WithNumber("limit",
			mcp.Description("Maximum number of repositories to return. Range from 1 to 100."),
			mcp.DefaultNumber(10),
			mcp.Min(1),
			mcp.Max(100),
		),
	)
}

// GetRepoDetailSchema 获取仓库详情的工具
func GetRepoDetailSchema() mcp.Tool {
	return mcp.NewTool(
		"GetRepoDetail",
		mcp.WithDescription("Get detailed information about a specific GitHub repository. This tool provides comprehensive data about a repository including stars, forks, commits, contributors, and more."),
		mcp.WithString("owner",
			mcp.Description("Owner (username or organization) of the repository."),
			mcp.Required(),
		),
		mcp.WithString("repo",
			mcp.Description("Name of the repository."),
			mcp.Required(),
		),
	)
}

// GetDeveloperDetailSchema 获取开发者详情的工具
func GetDeveloperDetailSchema() mcp.Tool {
	return mcp.NewTool(
		"GetDeveloperDetail",
		mcp.WithDescription("Get detailed information about a specific GitHub developer. This tool provides comprehensive data about a developer including their repositories, contributions, followers, and more."),
		mcp.WithString("username",
			mcp.Description("GitHub username of the developer."),
			mcp.Required(),
		),
	)
}

// GetLanguageStatsSchema 获取语言统计的工具
func GetLanguageStatsSchema() mcp.Tool {
	return mcp.NewTool(
		"GetLanguageStats",
		mcp.WithDescription("Get statistics about programming languages on GitHub. This tool provides insights into language popularity, growth rates, and usage statistics."),
		mcp.WithString("time_range",
			mcp.Description("Time range for the language statistics data. Choose from past 24 hours, past week, past month, past 3 months, past year, or all time to see statistics for different periods."),
			mcp.Enum(
				ossinsight.TimeRangePast24Hours,
				ossinsight.TimeRangePastWeek,
				ossinsight.TimeRangePastMonth,
				ossinsight.TimeRangePast3Months,
				ossinsight.TimeRangePastYear,
				ossinsight.TimeRangeAllTime,
			),
			mcp.Required(),
		),
		mcp.WithNumber("limit",
			mcp.Description("Maximum number of languages to return. Range from 1 to 100."),
			mcp.DefaultNumber(10),
			mcp.Min(1),
			mcp.Max(100),
		),
	)
}
